theme = "modern"
icons = "awesome5"

#[[block]]
#block = "focused_window"
#max_width = 50
#show_marks = "visible"


[[block]]
block = "net"
device = "wlan0"
format = " {ssid} {signal_strength} {ip} {speed_down;K*b} {speed_up;K*b} "
interval = 1

[[block]]
block = "backlight"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 1800
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

#[[block]]
#block = "cpu"
#interval = 1
#
#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

[[block]]
block = "sound"
headphones_indicator = true

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"


[[block]]
block = "weather"
format = "{weather_verbose} ({location}) {temp}, {wind_kmh} km/h {direction}"
service = { name = "openweathermap", api_key = "2133b62a2b070b4bfb69d6d53c5df74c", city_id = "1271306", units = "metric" }
interval= 1800


#[[block]]
#block = "hueshift"
#hue_shifter = "redshift"
#step = 50
#click_temp = 3500

